### ISSUE TITLE
Finish, recap, and clean up: Questions and TODO tasks

### ISSUE THREAD

**Issue by openmindculture** [openmindculture/IngoSFraktalistheme#2]
* [ ] system config service not working properly (see. 2022_1)
* [ ] logger not working properly (see 2021_3)
* [ ] incorrect / inconsistent capitalization of folder names?
* [ ] localize every hard-coded template string using snippets (lesson 10)
* [ ] we should not need a full path to loop over our custom data in twig
* [ ] analyze, fix, refactor using tooling (PhpStan, SonarLint, built-in PhpStorm tools, ...)
* [ ] recap, read, and understand everything that I did (would-be code review preparation)
